### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by BoWangXJTU** [PengNi/ccsmeth#1]
Hi Peng Ni,
When I install the methccs, but I got this error report as follows:

FileNotFoundError: [Errno 2] No such file or directory: '/home/wangbo/softwares/methccs-master/deepsmrt/_version.py'

Please get me a help.

Yours,
Bo

**Comment by PengNi** [comment]
Hi @BoWangXJTU , thanks for your interest. 

methccs has not been packaged yet. It is also lack of documentation, and  still under development. So now it cannot be installed. We are writing the paper about it, and hope we can done the work in months.

For now please use commands like `python methccs/align_subreads.py`.

Best,
Peng

**Comment by BoWangXJTU** [comment]
Thank you for your reply. This tool 'methccs' is a great work, and it will be a 'game changer' in PacBio HiFi methylation calling field. 
Best,
Bo

**Comment by PengNi** [comment]
closing this cause ccsmeth now can be installed.
