### ISSUE TITLE
about vocub_size

### ISSUE THREAD

**Issue by btwbtm** [PengNi/ccsmeth#12]
https://github.com/PengNi/ccsmeth/blob/dbc0cba01b5481eafa4de6285d0df15d17a0978b/ccsmeth/models.py#L31

Hi, nice project! But I am confused about this parameter. From my understanding, there are only four types of base, i.e. ATCG. Why you set the vocabulary size as 16? Thx!

**Comment by PengNi** [comment]
In most cases, 4 is enough. Using 16 considers the case that there are other IUPAC DNA/RNA bases in the sequence. See [IUPAC Codes](https://www.bioinformatics.org/sms/iupac.html).
