### ISSUE TITLE
Question:types of input, old data or just HiFi?

### ISSUE THREAD

**Issue by mikeds211** [PengNi/ccsmeth#13]
This looks exactly what I have been searching for, for some time. I have old sequel2 data but these are not the more recent HiFi. Before I invest my time in installing and testing this, can anyone tell me if this accepts normal, old sequel2 output files (i.e. non-HiFi files)?

**Comment by PengNi** [comment]
Hi @mikeds211 , sorry for the delay! Since v0.2.0, ccsmeth only accepts HiFi reads as input. However, I think the old sequel2 output files can be transformed to HiFi reads using the PacBio tool `pbccs`.

Best,
Peng

**Comment by mikeds211** [comment]
Thanks for the tip. Unfortunately pbccs is not available in conda for mac os. Only the linux version is available. That took me some time to work out. I will look around to see if there is some alternative.

**Comment by mikeds211** [comment]
It is not clear that this program will only work under linux. I was hoping to use it under Mac OS but while many of the pacbio tools are available on both linux and mac os, the pbccs tool is currently only available for linux. I have used pbccs in ubuntu within virtualbox to convert sequel2 data to HiFi, but now I realise that pbccs is also required for ccsmeth to run. To me, that means it is linux only. Is that correct?

**Comment by PengNi** [comment]
@mikeds211 , yes, some steps of ccsmeth requires pacbio tools, which means it is linux only.

Best,
Peng

**Comment by mikeds211** [comment]
OK, so now I've got linux running under virtualbox on my iMac, and the installation of ccsmeth went smoothly. I could convert my old sequel2 file to HiFi using ccs but "ccsmeth call_hifi" command (as shown in the code page) fails with the error, "FATAL | ccs ERROR: Missing base features for output kinetic mode: IPD or PulseWidth". Which probably means I needed to convert my sequel2 file to HiFi with one of the kinetics flags '-all-kinetics' or '-hifi-kinetics'.  
**Question**: Any ideas which one of the two types of flags I should use? 
I had thought the basic ccs command would retain the kinetic data in the original .bam file but I am guessing now that I have to process with the kinetic flag added. As an aside, I also have pacbiotools running in virtualbox too, so am hoping to be able to compare the results of ccsmeth with the pacbio kit.

**Comment by PengNi** [comment]
@mikeds211 , thank you very much for trying to use ccsmeth. 
  - `ccsmeth call_hifi` is actually a function which uses pbccs to call hifi reads from subreads. So if you had called hifi reads using pbccs, you don't have to use `ccsmeth call_hifi` again. 
  - Either  '-all-kinetics' or  '-hifi-kinetics' is ok to use, however I prefer '-hifi-kinetics'  which keeps only hifi reads.
  - At present, ccsmeth is under development, we haven't got a stable model for detcting 5mCpGs. I think I still need two or more weeks. I will release a stable model ASAP. And if the pacbiotools you are runnning are primrose/pb-CpG-tools, they are also great tools for 5mCpG detection and worth to try. 

Best,
Peng

**Comment by PengNi** [comment]
Also, I don't know if you have tried container (like docker or singularity) to run linux tools on Mac. I think it is more flexible than virtualbox.

**Comment by PengNi** [comment]
model for call_mods module released.
