### ISSUE TITLE
allele-specific methylation

### ISSUE THREAD

**Issue by yuntwang** [PengNi/ccsmeth#15]
Hi，Very good tool, I came here specially to ask you a question. 

In the article(**DNA 5-methylcytosine detection and methylation phasing using PacBio circular consensus sequencing**), Allele specific methylation is obtained by combining SNP of phase separation with Pacbio  CCS Reads. 

If I already have haplotype resolved genome, how to get allele-specific methylation?
1. use diploid genome instead of haplotype resolved genome as reference genome？
2. if used haplotype resolved genome as reference genome, how to use ccsmeth？
Extracted single set of reads，and then after analyzing.

Hope to hear from you,very thanks

**Comment by PengNi** [comment]
Hi @yuntwang, thanks very much for your interest. 
- I think you can try using haplotype resolved genome as reference. But I didn't test that case. 
- If a diploid genome is provided, then before `call_methylation from aligned bam`, the bam file must be haplotaged using whatshap. If you are using a haplotype resolved genome, I think you don't need to use whatshap. That's the difference I think. However, right now we haven't got a stable version of ccsmeth and its model, so I'm afraid that ccsmeth can't be used for analyzing yet. I will release a model ASAP.

Best,
Peng
