### ISSUE TITLE
Where is the master - models

### ISSUE THREAD

**Issue by hunkui1** [PengNi/ccsmeth#16]
Hello,
Where is the master - models, can I use model_cpg_attbigru2s_hg002_15kb_s2.b21_epoch7.ckpt?

**Comment by PengNi** [comment]
Hi @hunkui1 thanks for your interest of ccsmeth. Since ccsmeth v0.2.0, we have changed the pipeline of ccsmeth. So the prior model can't be used with master version of ccsmeth now. I will release a new model ASAP.

Best,
Peng

**Comment by hunkui1** [comment]
Hello，
Hello, is there any difference in the accuracy of methylation between CCSMEth V0.2.0 and CCSMEth V0.1.0？
Thank you!

**Comment by PengNi** [comment]
We are trying to get a higher accuracy with ccsmeth v0.2.0. But the main difference of the two versions is that, v0.1.0 takes subreads as input, which is very time-consuming, v0.2.0 takes hifi reads as input which is much faster.

**Comment by hunkui1** [comment]
This is a good piece of software.In the last few weeks, I have analyzed the genome in combination with the methylation data of V0.1.0 and GFF files. I hope you can make a breakthrough soon. 
Thank you

**Comment by hmyh1202** [comment]
Hi，  when to release a new model  ?

**Comment by PengNi** [comment]
model released.
