### ISSUE TITLE
how about cpg_tools of Pacbio

### ISSUE THREAD

**Issue by hmyh1202** [PengNi/ccsmeth#18]
Hello，
  
   what is the  different between Pacbio CpG tools and your ccsmeth software?  And where is the models can I get when using   --model_file /path/to/ccsmeth/models/model.ckpt

Thank you!

**Comment by PengNi** [comment]
Hi @hmyh1202 , thanks for your interest! pacbio_cpg_tools is great and has high performance. ccsmeth has a difference model architecture compared to primrose and pacbio_cpg_tools. However, at present we haven't trained a stable model of ccsmeth. I will release the model ASAP.

Best,
Peng

**Comment by hmyh1202** [comment]
Pacbio_cpg_tools only output very few CpG sites ~30M， the bismark for NGS 30x data can get &gt;40M CpG site. So, what`s the number of your tools can got in your test ? Thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengNi/ccsmeth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengNi/ccsmeth] how about cpg_tools of Pacbio (Issue #18)





 
Hi @hmyh1202 , thanks for your interest! pacbio_cpg_tools is great and has high performance. ccsmeth has a difference model architecture compared to primrose and pacbio_cpg_tools. However, at present we haven't trained a stable model of ccsmeth. I will release the model ASAP.
 
Best,
 Peng

**Comment by PengNi** [comment]
We also only output 30M CpGs, and 30M is the number of all the CpGs in human when only CpGs in forward strand are counted.  I think the reason that bismark outputs 40M CpGs, is that it treats the CpGs in reverse strand as different sites from the CpGs in forward strand, and outputs all of them if they are all covered by reads. However, in mammals, in most cases, the methylation status of cytosines at CpG on both DNA strands are symmetric( both methylated or both unmethylated). So it is ok only outputting CpGs in forward strand.

**Comment by hmyh1202** [comment]
Tanks for your reply！


 Yes， Bismark treats the CpGs&nbsp; in reverse strand as different from the forward strands, both forward and reverse cytosines are reported. Because semi-methylation of CpG dinucleotide also a point to disscuss. 



Another question， how can I caculate the methylation level of a region base on the 30M site?&nbsp; In general, total mC count/(total mC count +total unC count )&nbsp; is caculate for a region, or mC site num/(all C number of reference), so which method should select or any other method ? 



Thank you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengNi/ccsmeth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengNi/ccsmeth] how about cpg_tools of Pacbio (Issue #18)





 
We also only output 30M CpGs, and 30M is the number of all the CpGs in human when only CpGs in forward strand are counted.  I think the reason that bismark outputs 40M CpGs, is that it treats the CpGs in reverse strand as different sites from the CpGs in forward strand, and outputs all of them if they are all covered by reads. However, in mammals, in most cases, the methylation status of cytosines at CpG on both DNA strands are symmetric( both methylated or both unmethylated). So it is ok only outputting CpGs in forward strand.

**Comment by PengNi** [comment]
From my point, as we can give a binary label (0/1) of CpGs at each read, I think the `total mC count/(total mC count +total unC count ) at reads level` is a common method for measuring methylation level for a region.

**Comment by hmyh1202** [comment]
Fine, the 2st method is a mC density level. Thank you!
