### ISSUE TITLE
No local packages or working download links found for ('torch<=1.7.0,>=1.2.0')

### ISSUE THREAD

**Issue by mikeds211** [PengNi/ccsmeth#19]
Trying to install a working version of ccsmeth into Ubuntu running on virtual box on an iMac, and got the error message about PyTorch ("No local packages or working download links found for ('torch<=1.7.0,>=1.2.0')"). The Pytorch page has the stable version of 1.1 and a developer version of 1.8, and both are outside the range set in ccsmeth requirements. If one searches the pytorch site there are archived versions less than 1.8, but I don't know which of these are OK.

**Comment by PengNi** [comment]
torch<=1.11.0,>=1.2.0 is suggested now. A simple way to install ccsmeth environment is provided in README.
