### ISSUE TITLE
optimize ccsmeth call_mods procedure

### ISSUE THREAD

**Issue by PengNi** [PengNi/ccsmeth#20]
now ccsmeth call_mods: call mods -> save as per_readsite.tsv -> gathering per_read modinfo -> save as modbam format.

maybe call_mods -> directly save as modbam format is a better way.

**Comment by olaraym** [comment]
I think call_mods saving directly as modbam format is a better way because it will allow for calling the modification frequencies.

**Comment by PengNi** [comment]
see commit [6d5113d](https://github.com/PengNi/ccsmeth/commit/6d5113dd93c2b33da4eafd396c68f8e0727a0413)
