### ISSUE TITLE
A question about the output file

### ISSUE THREAD

**Issue by hunkui1** [PengNi/ccsmeth#23]
hi，I used this command：
`ccsmeth call_freqb --input_bam /home/lyx/wangaokai/data/pacbio_analyse/tden-mas/03.call_mods/r64114_20201106_074159.hifi.pbmm2.call_mods.modbam.bam --ref /home/lyx/wangaokai/data/genome/tden/Tden.genome.fasta --output ./r64114_20201106_074159.hifi.pbmm2.call_mods.modbam.feaq --threads 20 --sort
`
I got：
![a1f6b147fc12b0996429a47f9c2b7f9](https://user-images.githubusercontent.com/88669338/190574108-738ff44e-35ac-4f7e-abf9-0c4a854e05ac.jpg)
![21389c1987c446652b1add0198f19df](https://user-images.githubusercontent.com/88669338/190574183-ccb89378-4101-4351-b0e9-8a00f2bb9e7a.jpg)
This is different from the reference format in README. How do I understand it？

**Comment by PengNi** [comment]
@hunkui1 , the output has the first 10 columns (`chrom` to `modification_frequency`), but with `prob_0_sum`/`prob_1_sum` replaced with "-".

**Comment by hunkui1** [comment]
I see. Thank you for your answer.
