### ISSUE TITLE
Process stuck  when split the data.

### ISSUE THREAD

**Issue by cosineDaDa0623** [PengNi/ccsmeth#37]
Hi PengNi!
I recently installed the ccsmeth and encountered a problem when using it. When I call modification, the process stuck at 8%, and I cannot figure out why.
The command I used is 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 ccsmeth call_mods \
  --input /home/user/ydliu/pacbio/ccs_data/output.hifi.bam \
  --model_file /home/user/ydliu/cos/ccsmeth/models/model_ccsmeth_5mCpG_aggregate_attbigru_b11.v2p.ckpt \
  --output /home/user/ydliu/pacbio/ccs_data/output.hifi.call_mods \
  --threads 20 --threads_call 6 --model_type attbigru2s \
  --mode denovo
```
The log is as followed:
![image](https://github.com/PengNi/ccsmeth/assets/88964258/86855327-2baa-48fa-8310-669c1b23f1bd)
And after I reinstall the numpy, a new problem occurred.
![image](https://github.com/PengNi/ccsmeth/assets/88964258/f55861e1-2861-45ae-88b7-b545d148e5af)

**Comment by PengNi** [comment]
Hi @cosineDaDa0623 , 

Thanks for using ccsmeth. For `call_mods` module, the model ckpt file should be [model_ccsmeth_5mCpG_call_mods_attbigru2s_b21.v2.ckpt](https://github.com/PengNi/ccsmeth/blob/master/models/model_ccsmeth_5mCpG_call_mods_attbigru2s_b21.v2.ckpt). 
The [model_ccsmeth_5mCpG_aggregate_attbigru_b11.v2p.ckpt](https://github.com/PengNi/ccsmeth/blob/master/models/model_ccsmeth_5mCpG_aggregate_attbigru_b11.v2p.ckpt) file is for `call_freqb` module in aggregate mode. 

Best, 
Peng

**Comment by cosineDaDa0623** [comment]
```
CUDA_VISIBLE_DEVICES=0,1,2,3 ccsmeth call_mods \
  --input /home/user/ydliu/pacbio/ccs_data/output.hifi.bam \
  --model_file /home/user/ydliu/cos/ccsmeth/models/model_ccsmeth_5mCpG_call_mods_attbigru2s_b21.v2.ckpt \
  --output /home/user/ydliu/pacbio/ccs_data/output.hifi.call_mods \
  --threads 20 --threads_call 6 --model_type attbigru2s \
  --mode denovo
```
![image](https://github.com/PengNi/ccsmeth/assets/88964258/16a73b19-80df-467d-bd45-08cc60af05c3)
I changed the model, but it still stuck o(╥﹏╥)o

**Comment by PengNi** [comment]
The log said that you should install a pytorch which is compeatible with your CUDA version.

**Comment by PengNi** [comment]
Closing this issue as it is inactive. If further issues arise, feel free to reopen this issue.
