### ISSUE TITLE
A question about the frequency threshold determination

### ISSUE THREAD

**Issue by Wyinghao** [PengNi/ccsmeth#44]
I used the call_freqb as described and output the BED file, column 11 of the file is the frequency and likelihood of methylation sites, I would like to ask you if there is a recommended filter value (how much frequency should be greater) as a trusted methylation site.

**Comment by PengNi** [comment]
Hi @Wyinghao , thanks for using our tool. In my opinion, there's no common thresholds for methylated or unmethylated sites. It depends on the problem and the data. Generally, I would take >=0.7, <=0.3 to get highly methylated and lowly methylated sites, respectively. 

Best, 
Peng

**Comment by Wyinghao** [comment]
Hi，peng！Thank you very much for your reply，I will adopt this standard that you recommend！

**Comment by PengNi** [comment]
Closing this issue as it is inactive. If further issues arise, feel free to reopen this issue.
