### ISSUE TITLE
How to train a model to infer the site-level methylation frequency

### ISSUE THREAD

**Issue by Songmg-Nwafu** [PengNi/ccsmeth#45]
Hello @PengNi 

I want clarity on using the ccsmeth Train to train a new model for infering the site-level methylation frequency, but I don't find the description. Thanks.

**Comment by Songmg-Nwafu** [comment]
Hi @PengNi ,  I am still expecting your response. It is still unclear that training a new model for infering the site-level methylation frequency. I do not know how to extract features about it.

**Comment by PengNi** [comment]
Please refer the paper and these scripts.
[train_aggremode_regression.zip](https://github.com/PengNi/ccsmeth/files/13421435/train_aggremode_regression.zip)
