### ISSUE TITLE
ccsmeth train 

### ISSUE THREAD

**Issue by SarahChen0401** [PengNi/ccsmeth#6]
Hi Peng,
I would like to retrain your ccsmeth model using another ccs or clr dataset with corresponding WGBS data.  I am not sure about your "train_file", is it an aligned bam file, feature .tsv file formatted by step 2 'ccsmeth extract'?  How can I label the methylation level of every site or every ZMW? 
``` 
ccsmeth train -h
usage: ccsmeth train [-h] --train_file TRAIN_FILE --valid_file VALID_FILE
                     --model_dir MODEL_DIR
  --train_file TRAIN_FILE
  --valid_file VALID_FILE
```
Can you give me an example command? 
Thanks!
 
Best wishes,
Shuhua

**Comment by PengNi** [comment]
Hi Shuhua,

You can refer [this issue in deepsignal](https://github.com/bioinfomaticsCSU/deepsignal/issues/74). ccsmeth has a similar training procedure. For training it needs feature.tsv files extracted using high-confidence methylatied/unmethylated (in my tests I used methylation frequency in BS = 1.0/0.0 ) sites.

Best,
Peng
